development:
  adapter: mysql2
  database: doesnychavepower_dev
  username: root
  password: root
  host: localhost
  
test:
  adapter: mysql2
  database: doesnychavepower_test
  username: root
  password: root
  host: localhost

staging:
  adapter: mysql2
  database: doesnychavepower_staging
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: doesnychavepower_production
  username: root
  password: root
